module

public import ExactOverlaps.SelfSimilar.BernoulliBlocks
public import Mathlib.Probability.Martingale.Convergence
public import Mathlib.MeasureTheory.Function.FactorsThrough

/-!
Finite-coordinate conditional expectations approximate every integrable
measurable Bernoulli observable in L1. The approximation is an application
of Mathlib's proved martingale convergence theorem to an explicit growing
filtration whose supremum is the full product sigma-algebra.
-/

@[expose] public section

open MeasureTheory Filter
open scoped Topology ENNReal

namespace ExactOverlaps.Bernoulli

variable {A : Type*} [MeasurableSpace A]

/-- The sigma-algebra generated by coordinates `0,...,n`. -/
def prefixFiltration : Filtration ℕ (inferInstance : MeasurableSpace (ℕ → A)) where
  seq n := ⨆ k : Fin (n + 1), MeasurableSpace.comap (fun ω : ℕ → A ↦ ω k) inferInstance
  mono' n m hnm := by
    apply iSup_le
    intro k
    exact le_iSup_of_le (⟨k, by omega⟩ : Fin (m + 1)) le_rfl
  le' n := iSup_le (fun k ↦ (measurable_pi_apply (k : ℕ)).comap_le)

theorem prefixFiltration_eq_comap_block (n : ℕ) :
    prefixFiltration (A := A) n = MeasurableSpace.comap (block (n + 1) 0) inferInstance := by
  have heq : block (A := A) (n + 1) 0 =
      fun (ω : ℕ → A) (k : Fin (n + 1)) ↦ ω k := by
    funext ω k
    exact congrArg ω (Nat.zero_add _)
  rw [heq, MeasurableSpace.comap_process_pi]
  rfl

theorem iSup_prefixFiltration : (⨆ n, prefixFiltration (A := A) n) =
    (inferInstance : MeasurableSpace (ℕ → A)) := by
  apply le_antisymm (iSup_le (fun n ↦ prefixFiltration.le n))
  change (⨆ k : ℕ, MeasurableSpace.comap (fun ω : ℕ → A ↦ ω k) inferInstance) ≤ _
  apply iSup_le
  intro k
  apply le_iSup_of_le k
  exact le_iSup_of_le (⟨k, Nat.lt_succ_self k⟩ : Fin (k + 1)) le_rfl

theorem prefix_condExp_factors (p : Measure A) [IsProbabilityMeasure p]
    (f : (ℕ → A) → ℝ) (n : ℕ) :
    ∃ g : (Fin (n + 1) → A) → ℝ, Measurable g ∧
      (sequenceLaw p)[f | prefixFiltration n] = fun ω ↦ g (block (n + 1) 0 ω) := by
  have hm : StronglyMeasurable[prefixFiltration n]
      ((sequenceLaw p)[f | prefixFiltration n]) := stronglyMeasurable_condExp
  rw [prefixFiltration_eq_comap_block] at hm
  obtain ⟨g, hg, heq⟩ := hm.exists_eq_measurable_comp
  refine ⟨g, hg.measurable, ?_⟩
  simpa only [← prefixFiltration_eq_comap_block, Function.comp_def] using heq

theorem prefix_condExp_error_tendsto (p : Measure A) [IsProbabilityMeasure p]
    {f : (ℕ → A) → ℝ} (hfm : Measurable f) (hf : Integrable f (sequenceLaw p)) :
    Tendsto (fun n ↦ ∫ ω, |f ω - ((sequenceLaw p)[f | prefixFiltration n]) ω|
      ∂sequenceLaw p) atTop (𝓝 0) := by
  have hmeas : StronglyMeasurable[⨆ n, prefixFiltration n] f := by
    rw [iSup_prefixFiltration]
    exact hfm.stronglyMeasurable
  have h := hf.tendsto_eLpNorm_condExp (ℱ := prefixFiltration) hmeas
  have ht := (ENNReal.continuousAt_toReal ENNReal.zero_ne_top).tendsto.comp h
  simp only [ENNReal.toReal_zero] at ht
  apply ht.congr
  intro n
  simp only [Function.comp_apply]
  have hi : Integrable ((sequenceLaw p)[f | prefixFiltration n] - f) (sequenceLaw p) :=
    integrable_condExp.sub hf
  rw [eLpNorm_one_eq_lintegral_enorm hi.aestronglyMeasurable,
    ← integral_norm_eq_lintegral_enorm hi.aestronglyMeasurable]
  apply integral_congr_ae
  exact ae_of_all _ (fun ω ↦ by simp only [Pi.sub_apply, Real.norm_eq_abs, abs_sub_comm])

end ExactOverlaps.Bernoulli
